### ISSUE TITLE
Column-major memory layout

### ISSUE THREAD

**Issue by surgura** [surgura/Dynarray#2]
It's nicer to have the first dimension be laid out as a complete array.

**Comment by surgura** [comment]
Implemented in [v1.4](https://github.com/surgura/Dynarray/releases/tag/v1.4)

**Comment by WouterFlorijn** [comment]
OMG so nice!

![surgurasoft](https://cloud.githubusercontent.com/assets/7816704/21023919/e018ded2-bd82-11e6-9526-55e3edab6ef2.png)
